### ISSUE TITLE
typo in hyperlink to adoptopenjdk

### ISSUE THREAD

**Issue by gitt0h0** [eclipse/capella#2046]
On https://wiki.eclipse.org/Capella/Installation_Guide#Capella_Installation in the section 'Prerequisites Needed for Install'
the link to adoptopenjdk should end in .net and not in .ne as is the case now

**Comment by pdulth** [comment]
Hi, 
Indeed, the link isn't working and is misleading as AdoptOpenJDK is not embedded in Capella, its Open JDK from https://jdk.java.net.
