### ISSUE TITLE
Export as image fails

### ISSUE THREAD

**Issue by mehmetalianil** [eclipse/capella#2170]
I get the following error dialog when trying to export a diagram as an image:
![image](https://user-images.githubusercontent.com/551129/115212393-bf826d80-a100-11eb-83f2-fa04c26cf3b5.png)

Here is the model to reproduce. The diagram is [SAB] Preventive Maintenance Functional Chain
[sensor-model.zip](https://github.com/eclipse/capella/files/6334803/sensor-model.zip)

Capella

Version: 5.0.0
Build id: 202012021234

**Comment by pdulth** [comment]
Hi, 
I'm not able to reproduce on my side, the export is working on your model / diagram. 
Are you using windows version ?
Do you use "Right click on aird file / Export Representations as images" or in an opened diagram, the toolbar button ?


Can you attach the Error log in this issue, there might be something useful here
https://github.com/eclipse/capella/wiki/Send-Error-Log 

Thanks

**Comment by mehmetalianil** [comment]
I was using both right click on diagram- export as image and the toolbar
button.

Will produce error logs later today.

**Comment by mehmetalianil** [comment]
[Uploading image_export.log…]()
Here is the error log.

**Comment by mehmetalianil** [comment]
Update, the export functionality works in a clean workspace, and somehow is bothered with having a closed project beside it in the workspace. (Error log includes a line like MapleMoth project is closed.)

**Comment by jbNussas-sys** [comment]
Hello, 
We are facing the same issue on capella 6.1, just after having adding some sequence in a scenario.
We have changed the workspace. Doing the export on an other computer. same result
We check the export on different image format => same issue

When we export in HTML, it create 6 images an put it in html table.

Here is the error log :

> null
> org.eclipse.sirius
> Error
> Wed Jun 19 10:34:08 CEST 2024
> The following representation(s) failed to export as image:
> Too large representation(s): 
>  - name: [ES] Starting Mode (Physical view), type: Component Exchanges Scenario, target: [ES] Starting Mode (Physical view)

It's not possible to communicate our model (confidential).

It seems that the number of elements in the diagram trig the error.
