### ISSUE TITLE
Tempered jar content in Capella RCP Product : template.html file of nebula.widgets.richtext 

### ISSUE THREAD

**Issue by mPorhel** [eclipse/capella#2235]
While using the Capella bundle as a repository to build another product, I get the following error: 

> 14:54:16 [ERROR] An error occurred while transferring artifact canonical: osgi.bundle,org.eclipse.nebula.widgets.richtext,1.2.0.201711021145 from repository https://MyCustomMirroBasedOnCapellaProduct5.1.0:
> 14:54:16 [ERROR]    Problems downloading artifact: osgi.bundle,org.eclipse.nebula.widgets.richtext,1.2.0.201711021145.:
> 14:54:16 [ERROR]       File has invalid content:/tmp/signatureFile7108071569084742198.jar:
> 14:54:16 [ERROR]          Invalid content:org/eclipse/nebula/widgets/richtext/resources/template.html
> 14:54:16 [ERROR] Internal error: org.eclipse.tycho.repository.local.MirroringArtifactProvider$MirroringFailedException: Could not mirror artifact osgi.bundle,org.eclipse.nebula.widgets.richtext,1.2.0.201711021145 into the local Maven repository.See log output for details. The file "org/eclipse/nebula/widgets/richtext/resources/template.html" in the jar "/tmp/signatureFile7108071569084742198.jar" has been tampered! -> [Help 1]
> 14:54:16 org.apache.maven.InternalErrorException: Internal error: org.eclipse.tycho.repository.local.MirroringArtifactProvider$MirroringFailedException: Could not mirror artifact osgi.bundle,org.eclipse.nebula.widgets.richtext,1.2.0.201711021145 into the local Maven repository.See log output for details.

Capella builds alter the content of this jar at build time : some html templates are modified to correct a compatibility issue with IE/Edge.
This done in the _create_dropins_ execution of _maven-antrun-plugin_ from [Capella RCP Product pom](https://github.com/eclipse/capella/blob/master/releng/plugins/org.polarsys.capella.rcp.product/pom.xml):
```
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-antrun-plugin</artifactId>
...
<version>${antrun-version}</version>
  <executions>
    <execution>
      <id>create-dropins</id>
      <phase>package</phase>
        <goals>
          <goal>run</goal>
        </goals>
        <configuration>
          <target>
	   <!-- Create the dropins folder -->
           <mkdir. ...
             ...
           <!-- Modify Nebula Richtext's template to fix IE compatibility bug. To remove if Nebula patches this -->
           <replace dir="${project.build.directory}/products/org.polarsys.capella.rcp.product/linux/gtk/x86_64/plugins">
	     <include name="org.eclipse.nebula.widgets.richtext_*/org/eclipse/nebula/widgets/richtext/resources/template.html"/>
             <replacefilter token="&lt;meta charset=&quot;utf-8&quot;&gt;" value="&lt;meta charset=&quot;utf-8&quot;&gt;${line.separator}&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=EDGE&quot;&gt;"/
           </replace>
           <replace dir="${project.build.directory}/products/org.polarsys.capella.rcp.product/macosx/cocoa/x86_64/Capella.app/Contents/Eclipse/plugins">
             <include name="org.eclipse.nebula.widgets.richtext_*/org/eclipse/nebula/widgets/richtext/resources/template.html"/>
             <replacefilter token="&lt;meta charset=&quot;utf-8&quot;&gt;" value="&lt;meta charset=&quot;utf-8&quot;&gt;${line.separator}&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=EDGE&quot;&gt;"/>
           </replace>
           <replace dir="${project.build.directory}/products/org.polarsys.capella.rcp.product/win32/win32/x86_64/plugins">
             <include name="org.eclipse.nebula.widgets.richtext_*/org/eclipse/nebula/widgets/richtext/resources/template.html"/>
             <replacefilter token="&lt;meta charset=&quot;utf-8&quot;&gt;" value="&lt;meta charset=&quot;utf-8&quot;&gt;${line.separator}&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=EDGE&quot;&gt;"/>
           </replace>
         </target>
       </configuration>
    </execution>
```

The alteration of the html/jar should be mentioned somewhere (I did not look for this).
The product signatures files might maybe be modified to correspond to what it provided in the RCP. (The modification should maybe be done before the package phase in the local tp/repo and not after the construction of the bundle.

Does this modification correspond to an open bug on Nebula ?

Having the current messages might let think that some corruption has occurred after the build.

**Comment by pdulth** [comment]
Hi, 
yes, its due to https://github.com/eclipse/capella/issues/1509
the nebula issue https://bugs.eclipse.org/bugs/show_bug.cgi?id=521983 has been also in the meantime, so this pom.xml fix can be cleaned up.

**Comment by pdulth** [comment]
Same patch on Kitalpha product
https://github.com/eclipse/kitalpha/blob/535c203b1d1dea70ec812e3e16d2175ba18a0712/releng/plugins/org.polarsys.kitalpha.releng.sdk.product/pom.xml

And Capella studio
https://github.com/eclipse/capella-studio/blob/master/releng/plugins/org.polarsys.capella.studio.releng.product/pom.xml#L77

**Comment by arnauddieumegard** [comment]
The Nebula modification is done in https://github.com/eclipse/nebula/commit/a4ed87546b76b62c51a02689028632478c9f64c0 and so integrated in version 2.0.0.
