### ISSUE TITLE
[story image] The rich text editor can be very long to display the content

### ISSUE THREAD

**Issue by lfasani** [eclipse/capella#2396]
Steps to reproduce
* open the attached capella project from [testCapellaWithLargeDescription.zip](https://github.com/eclipse/capella/files/8707378/testCapellaWithLargeDescription.zip)
* open the Properties view
* select "Root Operational Activity"
* select the description tab
-> it is very long to display

**Comment by pdulth** [comment]
After some tests, it seems it breaks the wizard edition

- Add a description on an element
- Double click on the element in project explore
- Edit the description through the wizard, save, ok
- the Property view still keep the previous text.

![Fix](https://user-images.githubusercontent.com/34767327/169032830-0f92cb08-2a6b-4cf5-95ae-adcc02eab249.gif)
