### ISSUE TITLE
Bug in mass editing view

### ISSUE THREAD

**Issue by NiPelissier** [eclipse/capella#2557]
Version of Capella :
Version: 6.0.0
Build id: 202209090800

Issue : After selection multiple elements, and creating a mass editing view, the mass editing view isn't shown properly
![image](https://user-images.githubusercontent.com/92404770/214583359-d57ee2a3-b06d-498e-88ec-1496d01f6de2.png)
![image](https://user-images.githubusercontent.com/92404770/214583721-abe2fc97-cfa3-45f3-80ab-67bde18e477c.png)

**Comment by pdulth** [comment]
Hi, 
This has been fixed in the upcoming 6.1 (https://github.com/eclipse/capella/issues/2509)
This is occuring if you open a diagram first before opening the mass editing view.

As a workaround on 6.0, when you start Capella, make sure to open one Mass Editing view before opening any diagrams.
